deployments:
  odoo:
    kubernetes_helm_chart: bitnami/odoo
    kubernetes_helm_parameters: 
      bitnami/odoo: odooPassword=password,odooUser=root,odooUserEmail=root@com.com
    deployment_type: kubernetes
    kubernetes_service: odoo
    kubernetes_helm_repository: bitnami https://charts.bitnami.com/bitnami    
  drupal:
    kubernetes_helm_chart: stable/drupal
    deployment_type: kubernetes
    kubernetes_helm_parameters: 
      stable/drupal: drupalPassword=$ODOO_PASSWORD
    kubernetes_service: drupal
  apache:
    kubernetes_helm_chart: bitnami/apache
    deployment_type: kubernetes
    kubernetes_service: apache
    kubernetes_helm_repository: bitnami https://charts.bitnami.com/bitnami
  airflow:
    kubernetes_helm_chart: bitnami/airflow
    deployment_type: kubernetes
    kubernetes_helm_parameters: service.port=80,airflow.auth.username=my-user,airflow.auth.password=my-password
    kubernetes_service: airflow
    kubernetes_helm_repository: bitnami https://charts.bitnami.com/bitnami
