deployments:
  MyAppName:
    kubernetes_manifest: 
      - pod.yml
      - pod2.yml
    deployment_type: kubernetes
    kubernetes_default_image: redmine
    kubernetes_port_mapping: rss-site:8080:80
    subdomain_port_mapping: rss-site:8080
    port_forwarding: 80:3000
