deployments:
  odoo:
    kubernetes_helm_chart: bitnami/odoo
    kubernetes_helm_parameters: 
      stable/odoo: odooPassword=${ODOO_PASSWORD},odooUser=root,odooUserEmail=root@com.com
    deployment_type: kubernetes
    kubernetes_service: odoo
    kubernetes_helm_repository: bitnami https://charts.bitnami.com/bitnami    
  drupal:
    kubernetes_helm_chart: stable/drupal
    deployment_type: kubernetes
    kubernetes_service: drupal
  apache:
    kubernetes_helm_chart: bitnami/apache
    deployment_type: kubernetes
    kubernetes_service: apache
    kubernetes_helm_repository: bitnami https://charts.bitnami.com/bitnami
