deployments:
  default:
    dockerimage: r.cfcr.io/wisedrette/wisedrette/dockertest:master
    port_forwarding: 80:80
    docker_registry:
      server: r.cfcr.io
      username: wisedrette
      password: $REGISTRY_PASSWORD  
