deployments:
  odoo:
    kubernetes_helm_chart: stable/odoo
    deployment_type: kubernetes
    kubernetes_service: telling-rottweiler-odoo
  drupal:
    kubernetes_helm_chart: stable/drupal
    deployment_type: kubernetes
