deployments:
  MyAppName:
    dockerimage:
      python:3.8-alpine
    shell: sh
    build_steps:
      - apk update && apk upgrade && apk add --no-cache bash git openssh
      - pip install setuptools pip --upgrade --force-reinstall
      - pip install mezzanine
      - mezzanine-project myproject
      - cd myproject
      - sed -i -e 's/ALLOWED_HOSTS.*/ALLOWED_HOSTS = ["*"]/' myproject/settings.py
      - sed -i -e 's/ALLOWED_HOSTS.*/ALLOWED_HOSTS = ["*"]/' myproject/local_settings.py
      - python manage.py createdb --noinput
    launch_steps:
      python manage.py runserver 0.0.0.0:8000
    port_forwarding:
      80:8000

